create table if not exists allset_emails (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamp with time zone default now()
);

create table if not exists allset_contact_submissions (
  id bigint generated by default as identity primary key,
  name text,
  email text not null,
  message text not null,
  created_at timestamp with time zone default now()
);

create table if not exists allset_email_template_data (
  id bigint generated by default as identity primary key,
  template text not null,
  data text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists allset_cta_config (
  id bigint generated by default as identity primary key,
  cta_type text not null, -- 'ebook-delivery', 'newsletter', or 'welcome'
  template_data_id bigint not null references allset_email_template_data(id),
  newsletter_frequency text, -- 'daily', 'weekly', 'monthly' (nullable)
  updated_at timestamp with time zone default now()
);

-- alter table allset_emails enable row level security;
-- create policy "Allow all" on allset_emails for all using (true);

-- alter table allset_contact_submissions enable row level security;
-- create policy "Allow all" on allset_contact_submissions for all using (true);

-- Site settings (single row)
create table if not exists allset_site_settings (
  id bigint primary key check (id = 1),
  whatsapp_enabled integer not null default 0,
  whatsapp_phone text not null default '',
  whatsapp_message text not null default '',
  whatsapp_position text not null default 'bottom-right',
  assistant_enabled integer not null default 0,
  booking_widget_enabled integer not null default 1,
  site_language text not null default 'en-us',
  landing_content jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
